"""empty message

Revision ID: 8776b4bf0b0a
Revises: 814bb6430a95
Create Date: 2025-09-22 21:28:33.291520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8776b4bf0b0a'
down_revision = '814bb6430a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
